name: Lambda url-to-html
on:
  push:
    paths:
      - 'aws/lambda/url-to-html/src/**'
  pull_request:
    paths:
      - 'aws/lambda/url-to-html/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "The working directory is ${{ github.workspace }}"
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v2
      with:
        node-version: "20"
    - name: npm ci
      env:
        CI: true
      run: |
        npm ci 
      working-directory: "aws/lambda/url-to-html/src/"
    - name: Run the tests
      run: |
        npm test
      working-directory: "aws/lambda/url-to-html/src/"